include sys/socket.h before net/if_arp.h (#825)
On least OpenBSD this is required as otherwise the build fails with:
/usr/include/net/if_arp.h:79:18: error: field has incomplete type 'struct sockaddr'