BUILDFIX: add missing header for g++13
With g++13, the following error is produced:

```
src/metrics/../abstract_subnet_counters.hpp:79:28: error: 'std::function' has not been declared
```

Fix this error by including additional header.