For Fedora 36 libgpr requires libabsl dependencies.
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/libgpr.so: undefined reference to symbol '_ZN4absl12lts_202103245Mutex4LockEv'
/usr/bin/ld: /usr/lib64/libabsl_synchronization.so.2103.0.1: error adding symbols: DSO missing from command line